### PR TITLE
Use vagrant global-status instead of querying the hypervisor

### PR DESCRIPTION
**Pull request by myrjola**
This PR is not yet ready for merge, I'm just opening a discussion.

At least Virtualbox gives incorrect box names when having [multiple machines](http://docs.vagrantup.com/v2/multi-machine/) defined in the Vagrantfile. I think it would be better to tap into Vagrant's global-status command which has the following format:

```
$ vagrant global-status
id       name    provider   state   directory
--------------------------------------------------------------------------------
7bd9dc0  default virtualbox aborted /Users/martin/git/processor-fastorm
8221458  gateway virtualbox running /Users/martin/git/system-management/ansible
b5c95c9  centos7 virtualbox running /Users/martin/git/system-management/ansible
968d483  centos6 virtualbox running /Users/martin/git/system-management/ansible

The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date. To interact with any of the machines, you can go to
that directory and run Vagrant, or you can use the ID directly
with Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```

In my case vagrant-tramp gave results like ansible_gateway which wasn't approved by Vagrant.

Pros:
- The box ID:s work globally
- No need for hypervisor specific code in the bash script

Cons:
- The global-status command output format can change
- The tramp autocomplete now only suggests ID:s maybe it's possible to show the box name and use the ID internally, but it probably involves [advicing tramp functions](http://www.emacswiki.org/emacs/TrampAndDocker)

What do you think?

### CODE REVIEW

**Comment by dougm** [comment]
@myrjola Apologies for the delayed response.  I think it'd be great to use global-status instead, should solve most of the virtualbox related issues that I can't help with as I'm only using vagrant-tramp.el with Fusion.  I did briefly have a look at using global-status for this purpose when it was introduced, but it was rather slow.  I wonder if we could use ~/.vagrant.d/data/machine-index/index directly?

**Comment by myrjola** [comment]
@dougm Thanks for getting back to me. Now that I have your approval I will start to shape this code to a mergeable state. First I'll wait to see if the Vagrant-developers will consider my pull request https://github.com/mitchellh/vagrant/pull/6237. It adds support for JSON-output to the global-status command for a much more robust integration with vagrant-tramp.

Regarding the performance of the global-status command I hope its sufficient. For me the command completes in 0.8 seconds. If performance starts to be a problem I'm sure we can introduce a caching mechanism.

**Comment by dougm** [comment]
@myrjola sounds good, using global-status should make things more stable/portable.  Agreed we can take a look at the performance later if needed.

**Comment by marsam** [comment]
Hi, I've a vagrant plugin to output `global-status` in a machine readable format (csv) https://github.com/marsam/vagrant-info, maybe you can find useful

**Comment by myrjola** [comment]
Thanks for the info @marsam! I will consider your plugin if the Vagrant-devs won't merge my pull request that makes JSON-output possible for `global-status` https://github.com/mitchellh/vagrant/pull/6237. It has been silent so far, but I'll give them one month to answer.

**Comment by myrjola** [comment]
Closing this PR in favor of #17.

**Pull request closed without merging**
