### PR TITLE
Use screenshots to demonstrate features

### PR DESCRIPTION
**Pull request by ryanprior**
Do you like these better than the text examples we have now? Can they be better yet?

### CODE REVIEW

**Comment by dougm** [comment]
:+1: Looks good.  Animated gifs may work well too.  Thought I saw an Emacs package for that, but haven't looked into it.

**Comment by ryanprior** [comment]
Okay, I took a stab at animated gifs. I might want to try again after learning more about the tools involved, these are kinda shabby. But check out https://github.com/ryanprior/vagrant-tramp/tree/animated to see my progress.

**Comment by dougm** [comment]
Cool, interested to hear about the tools you used to create them.  Fine with me to merge whichever set you prefer, they are both much better than the old text version!

**Comment by ryanprior** [comment]
I decided to try `camcorder-mode`, which relies upon `recordmydesktop` and your choice of either `ffmpeg` or `mplayer` + `imagemagick`, of which I opted for the latter.

I was not satisfied with the default `convert` pipeline provided by camcorder-mode, which was producing gifs which weighed many megabytes. I played with flags, eventually settling on

    convert output/* -layers Optimize out.gif

I'm still unsatisfied with three things:
1. the borders of the video don't snap flush with the borders of the Emacs frame, leaking a little of my desktop behind. I don't know yet whether this is an issue with `recordmydesktop` or with how `camcorder-mode` invokes it.
2. the movie-to-gif transition messes with the timing: for example, when I tried to pause to let the viewer take in the image, this gets turned into a rapid series of cursor blinks with little pause.
3. camcorder-mode displays a message, "Camcorder mode enabled", which shows at the beginning of each movie and seems like unnecessary advertising. As I invoked it with M-x, ido also shows it first when I hit M-x again. It's altogether too conspicuous for my liking. But of these three issues, this one bothers me the least.

**Comment by ryanprior** [comment]
I've solved point 2 to my satisfaction using a routine like this:

    mkdir -p output
    avconv -i screencast.ogv -r 20 output/output-%4d.png
    convert output/* -fuzz 10% -layers optimize-frame -delay 5 screencast.gif

This has a number of benefits over what I was doing before:
* using png instead of jpeg as for the intermediate frames reduced visual artifacts
* using fuzz to reduce file size previously increased the visual artifacts to the point that they distracted me, but using png instead of jpeg, we can reduce file size to <1mb with minimal quality loss
* by outputting more frames using `r 20` in `avconv` and adding `delay 5` to the gif conversion, the timings better match the video

**Comment by dougm** [comment]
:+1: Nice!  Thanks for sharing the details on how you created these.  I'm going to give it a try at some point for another .el project (not yet released).

**Pull request closed without merging**
